import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(data) {
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        {/* {data.data.map((item)=>{
           <p className={styles.description}>
           Hello there - {item.id}
          </p>
        })}
        */}
        <p className={styles.description}>
           Yo {data.data.name}
        </p>

        <p className={styles.description}>
        {data.data.name} has ID: {data.data.id}
        </p>

      </main>

    </div>
  )
}


export async function getServerSideProps(){
  const res = await fetch('http://localhost:3000/api/hello')
  console.log(res);
  const data = await res.json()
  return { props : {data} }
}